// See https://aka.ms/new-console-template for more information
Console.WriteLine("Hello, World!");
Console.WriteLine("The current time is " + DateTime.Now);
string MyWorld = "My World is a Marvel";
Console.WriteLine(MyWorld);
MyWorld = MyWorld.Replace("World", "Life");
Console.WriteLine(MyWorld);
string SongLyrics = "Nothing else matters, except love";
var result = SongLyrics.StartsWith("love");
Console.WriteLine(result);
Console.WriteLine(SongLyrics.Contains("matters"));
string SongLyrics1 = "Love of my life, you've hurt me";
var result1 = SongLyrics1.StartsWith("Love");
Console.WriteLine(result1);
Console.WriteLine(SongLyrics1.Contains("life"));
int character = 1;
int energy = 2;
int creativity = 3;
int health = 4;
int intuition = 5;
int labour = 6;
int luck = 7;
int duty = 8;
int memory = 9;
int bernello = character + energy + creativity + health + luck + duty + memory;
int division = energy / creativity;
Console.WriteLine(bernello);
Console.WriteLine($"quotient: {division}");
int division2 = luck / energy;
Console.WriteLine($"quotient: {division2}");
int max = int.MaxValue;
int min = int.MinValue;
Console.WriteLine($"The range of integers is {min} and {max}");
int what  = max + 3;
Console.WriteLine($"An example of overflow: {what}");
double max2 = double.MaxValue;
double min2 = double.MinValue;
Console.WriteLine($"The range of double is {min2} to {max2}");
double third = 1.0 / 3.0;
Console.WriteLine(third);